name: Debug APK Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  debug-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install NDK
        run: sdkmanager "ndk;25.2.9519653"

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build debug APK
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_SDK_ROOT }}/ndk/25.2.9519653
        run: ./gradlew clean assembleDebug --stacktrace

      - name: Upload debug APK
        uses: actions/upload-artifact@v5
        with:
          name: LibreTube-debug-apk
          path: app/build/outputs/apk/debug/*.apk
